"""remove_permit_number_and_tags_columns

Revision ID: 1dedac8d27f3
Revises: 
Create Date: 2025-09-01 11:48:56.569614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dedac8d27f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('work_permits', 'risk_mitigation_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('work_permits', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_work_permits_permit_number', table_name='work_permits', postgresql_where='(permit_number IS NOT NULL)')
    op.drop_column('work_permits', 'tags')
    op.drop_column('work_permits', 'permit_number')
    op.drop_column('work_permits', 'duration_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_permits', sa.Column('duration_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('work_permits', sa.Column('permit_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('work_permits', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_work_permits_permit_number', 'work_permits', ['permit_number'], unique=False, postgresql_where='(permit_number IS NOT NULL)')
    op.alter_column('work_permits', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('work_permits', 'risk_mitigation_actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('documents', 'keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###